[[rule]]
name = "default"
include = ["*.rs"]
exclude = ["target/**"]
branches = ["if", "guard", "switch", "loop", "catch", "boolean-operator", "try"]
max_complexity = 15
max_methods = 12
max_lines = 400
max_declarations = 20
max_comment_lines = 90
max_comments = 45
